server:
  port: 8080
spring:
  datasource:
    username: root
    password: xuxiao
    url: jdbc:mysql://localhost:3306/blog??useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
