server:
  port: 8080
spring:
  datasource:
    username: root
    password: xuxiao
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#静态资源光放行不行，还要配置路径
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: static/**


#showSQL
logging:
  level:
    com:
      xx:
        blog:
          mapper: debug

package:
  controller: com.xx.blog.controller
  entity: com.xx.blog.entity
  mapper: com.xx.blog.mapper
  service: com.xx.blog.service
  impl: com.xx.blog.service.impl
